<?php
/**
 * @file
 * Availability information for ding objects.
 */

// Load Field module hooks.
module_load_include('inc', 'ding_availability', 'ding_availability.field');

/**
 * Implements hook_menu().
 */
function ding_availability_menu() {
  $items['ding_availability/items'] = array(
    'title' => 'Availability status',
    'page callback' => 'ding_availability_js',
    'access arguments' => array('access content'),
    'delivery callback' => 'ajax_deliver',
    'type' => MENU_CALLBACK,
  );

  $items['ding_availability/holdings'] = array(
    'title' => 'Availability and holding status',
    'page callback' => 'ding_availability_holdings_js',
    'access arguments' => array('access content'),
    'delivery callback' => 'ajax_deliver',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_ding_provider_user().
 */
function ding_availability_ding_provider_user() {
  return array(
    'availability' => array(
      'required' => TRUE,
      'install time setup' => TRUE,
    ),
  );
}

/**
 *
 */
function ding_availability_js($provider_ids) {
  $data = $_POST['availability'];
  drupal_json_output(ding_availability_items(explode(',', $provider_ids)));
}

/**
 *
 */
function ding_availability_holdings_js($provider_ids = NULL) {
  $commands = array();
  $availability = $_POST['availability'];
  
  $holdings = $_POST['holdings'];
  if(is_array($availability) && is_array($holdings))
    $ids = array_merge($availability, $holdings);
  else
    $ids = is_array($availability) ? $availability : $holdings;
  $data = ding_availability_holdings($ids);
  
  if(is_array($availability)) {
    // Set availability
    foreach($availability as $html_id => $avid) {
      if(isset($data[$avid])) {
        $return = theme('ding_availability_status', array('availability' => $data[$avid]));
        $commands[] = ajax_command_replace('#' . $html_id, $return);
      } else {
        $default_data = array(
          'local_id' => $avid,
          'available' => 0,
          'reservable' => 0,
          'show_reservation_button' => 0,
          'reserved_count' => 0,
          'deferred_period' => FALSE,
  	      'is_periodical' => 0,
          'is_internet' => TRUE,
          'status' => 'unavailable',
        );
        $return = theme('ding_availability_status', array('availability' => $default_data));
        $commands[] = ajax_command_replace('#' . $html_id, $return);
      }
    }
  }
  if(is_array($holdings)) {
    // Set holdings
    foreach($holdings as $html_id => $avid) {
      if(empty($data[$avid]) || !isset($data[$avid])) {
        $data[$avid]['location']['holdings'][][] = t('Not provided');
      }
      $return = theme('ding_availability_holdings', array('holdings' => $data[$avid]));
      $commands[] = ajax_command_html('#' . $html_id, $return);
    }
  }
  
  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

/**
 *
 */
function ding_availability_items($provider_ids) {
  if (ding_provider_implements('availability', 'items')) {
    $items = ding_provider_invoke('availability', 'items', $provider_ids);
    if (!$items) {
      return array();
    }
    foreach ($items as &$item) {
      $item += array(
        'reservable' => FALSE,
        'available' => FALSE,
      );
      _ding_availability_text($item);
    }
  }
  else {
    $items = ding_availability_holdings($provider_ids);
  }

  return $items;
}

/**
 *
 */
function ding_availability_holdings($provider_ids) {
  $items = ding_provider_invoke('availability', 'holdings', $provider_ids);
  if (!$items) {
    return array();
  }
  foreach ($items as &$item) {
    $item += array(
      'reservable' => FALSE,
      'available' => FALSE,
      'holdings' => array(),
    );
    _ding_availability_text($item);
  }

  return $items;
}

/**
 * Adds the human readable status text of an item.
 */
function _ding_availability_text(&$item) {
  if (isset($item['status']) && $item['status'] == 'inAcquisition') {
    $item['status'] = t('in acquisition');
  }
  elseif (($item['available'] && $item['reservable']) || $item['is_internet']) {
    $item['status'] = t('available');
  }
  elseif (!$item['available'] && $item['reservable']) {
    $item['status'] = t('on loan');
  }
  elseif ($item['available'] && !$item['reservable']) {
    $item['status'] = t('not reservable');
  }
  elseif (!$item['available'] && !$item['reservable']) {
    $item['status'] = t('unavailable');
  }
}


/**
 * Implements hook_block_info().
 * Define availability legend block.
 */
function ding_availability_block_info() {
  return array(
    'legend' => array(
      'info' => t('Ding availability legend'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ),
  );
}

/**
 * Implements hook_block_view().
 * Define availability legend block.
 */
function ding_availability_block_view($delta = '') {
  $block['subject'] = t('Ding availability legend');
  $block['content'] = ding_availability_render_legend();
  return $block;
}

/**
 * Return rendered legend block for availability types.
 */
function ding_availability_render_legend() {

  drupal_add_css(drupal_get_path('module', 'ding_availability') . '/css/ding_availability_legend.css');

  // construct the image's path (.gif stored in a module subdir)
  $image_path = drupal_get_path('module', 'ding_availability') . '/images/blank.gif';

  // make some text, image's alt & title tags (SEO, accessibility)
  $availability_legend['available']     = t('Available');
  $availability_legend['on-loan']       = t('On loan');
  $availability_legend['unavailable']   = t('Unavailable');
  $availability_legend['unreservable']   = t('Not reservable');

  // render image html using theme_image (returns NULL if file doesn't exist)
  foreach ( $availability_legend as $key => $val ) {
    $format_label = '<span class="availability-label">' . $val . '</span>';
    $format_image = theme('image', array('path'=>$image_path, 'alt'=>$val, 'title'=>$val));
    $format_items[] = '<div class="availability-legend-item ' . $key . '">' . $format_image . $format_label . '</div>';
  };
  $format_items[] = '<div class="clearfix"></div>';

  return '<div class="availability-legend">' . implode($format_items) . '</div>';

}

/**
 * ting_object_entities preprocessor.
 */
function ding_availability_preprocess_ting_object_entities(&$variables) {
  if (!empty($variables['content']) && function_exists('ding_availability_render_legend')) {
    $variables['content']['availability_legend'] = array(
      '#markup' => ding_availability_render_legend(),
      '#weight' => -10,
    );
  }
}

/**
 * Implements hook_theme
 */
function ding_availability_theme($existing, $type, $theme, $path) {
  return array(
    'ding_availability_holdings' => array(
      'variables' => array('holdings' => array()),
      'file' => 'ding_availability.theme.inc',
    ), 
    'ding_availability_status' => array(
      'variables' => array('availability' => NULL),
      'file' => 'ding_availability.theme.inc',
    ), 
  );
}